### ISSUE TITLE
Update /summit (2018 DKAN Summit)

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/ops#137]
https://getdkan.org/summit/
=============

## To-Dos

- [ ] Fix dates
- [ ] Fix copy
- [ ] Fix attendee list
- [ ] Make sure there are prominent links sending folks to sign up for the DKAN newsletter / DKAN Slack.
- [ ] Put in an official registration form
- [ ] Start posting about #dkansummit

**Comment by kimwdavidson** [comment]
Things to add:
- [x] Date: August 22nd
- [x] Time: 1-4pm
- [x] Location: Natcher Conference Center, Room C1/C2
- [x] Description: The 2018 DKAN Summit brings together the Drupal open data community to share, collaborate, and learn about using DKAN to support their open source open data efforts. We'll discuss what's new in DKAN, open data, and what's in store the future. We'll also work together to develop ideas for improvements to the platform, share what community members are working on, and discuss how to get involved in contributing to the project. You'll make lots of great connections to other members of the open source open data community, learn best practices, and contribute toward creating a better platform for everyone.
- [x] Registration link: https://www.eventbrite.com/e/2018-dkan-open-data-summit-tickets-36891515516
- [x] Agenda
- Introduction and State of DKAN
-- What's new in DKAN
- DKAN Science
--- Learn about our new module for science and research organizations
- DKAN and Drupal 8
-- Hear about the plans for a new version of DKAN in the latest version of Drupal and how you can get involved
- Lightning talks
-- The DKAN community shares their work in open data
- Discussion and Unconference time
-- A space to discuss broader needs of the open data community, improvements you'd like to see to DKAN, contributing to the platform, or to get into the nitty gritty of using a particular part of DKAN

**Comment by kimwdavidson** [comment]
@lukefretwell: this is ready for the website

**Comment by lukefretwell** [comment]
@kimwdavidson can you post in the embed code?

**Comment by lukefretwell** [comment]
@kimwdavidson NM I got it.

**Comment by lukefretwell** [comment]
@kimwdavidson updated:

https://getdkan.org/summit/

@stefaniefgray note changes but also:

* be sure to follow convention (photo naming sizing)
* QA thoroughly or do PR and/or let me know when new updates are made (all the 'CivicActions' text under speakers were going to Granicus)
* be mindful of coding tab/spacing (keep it clean)
