### ISSUE TITLE
Announce Roadmap

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/ops#87]
Here are some pre-made checklists based on your issue needs. Edit as you see fit. :-)

## Blog

How to contribute to the [DKAN blog](https://medium.com/dkan-blog):

* [ ] Create a shared, commentable Google doc (use [this template](https://docs.google.com/document/d/1K1sU9H2vPN5tnXqW7jQO2OCIM1TwEiC8AfNQv9k64PA/edit?usp=sharing)).
* [ ] When done, add a link to the Google doc to this issue (see 'Doc for review' below) with edit access for getdkan@gmail.com.
* [ ] Once editorial is finalized, publish your post to [Medium](https://medium.com/).
* [ ] Add your Medium username (see 'Medium username' below) to the GitHub issue ticket, we'll add you as a contributor and publish your post to the DKAN blog.

* Doc for review: 
* Medium username: 

## Promote

Checklist for promoting DKAN releases, blog posts and other news:

* [ ] Blog post (Instructions: https://github.com/GetDKAN/ops/wiki/Blog)
* [ ] Post to Twitter: https://twitter.com/getdkan
* [ ] Post to [DKAN Slack](https://dkan.slack.com) in #general, #buzz, or other relevant channels

**Comment by kimwdavidson** [comment]
Here's the text to intro the roadmap: https://docs.google.com/document/d/1Q8_ziFLzYInvWG1WneTtXej1x9lsz75__UBY5ttMQ4M/edit

To do:
@stefaniefgray: to find documentation on how to contribute
Kim to create clean, read only roadmap doc

**Comment by lukefretwell** [comment]
@kimwdavidson I can't access ^^.

**Comment by lukefretwell** [comment]
@kimwdavidson I created a new doc using the DKAN template. Let's work from this:

https://docs.google.com/document/d/1-C3M2Yocxh2aKDQ1Y53R7yhD7YAGtFdC7SYv8JqjaC4/edit?usp=sharing

**Comment by lukefretwell** [comment]
https://medium.com/dkan-blog/dkan-roadmap-b3e32d4132e
