### ISSUE TITLE
Docs aesthetic clean-up

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#90]
- [ ] delete advertisement in sidebar
- [ ] change a + a:visited link color to #0071BC
- [ ] change .wy-side-nav-search background-color to #0071BC
- [ ] add 'Docs' to DKAN at top of leftnav so it says 'DKAN Docs'
- [ ] change body color to #212121
- [ ] change heading (h1, h2, h3, ...) styles to:

```
font-family: 'Lato', sans-serif;
font-weight: 900;

```

**Comment by lukefretwell** [comment]
Moved to https://github.com/GetDKAN/dkan/issues/2291
