### ISSUE TITLE
Engagement checklist

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/ops#97]
For social media check-in:

- [x] Review and update social media wiki page
- [x] Create engagement checklist
- [x] Post to social media page in wiki
- [x] Add link to ^^ section in calendar invite

**Comment by lukefretwell** [comment]
@kimwdavidson @stefaniefgray of note:

* New engagement checklist (feel free to add to): https://github.com/GetDKAN/ops/wiki/Social-media#engagement-checklist
* Slack new member welcome letter (@stefaniefgray if you could own, that would be great - I sent to the last three folks that joined: https://github.com/GetDKAN/ops/wiki/Social-media#slack
* Minor edits to social media page: https://github.com/GetDKAN/ops/wiki/Social-media

@stefaniefgray link to the engagement checklist is now in the recurring calendar reminder
